repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        language: system
        entry: clang-format --dry-run --Werror
        types_or: [c++, c]
        exclude: ^build/
