repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        language: system
        entry: clang-format --Werror
        types_or: [c++, c]
        exclude: ^build/

      - id: clang-tidy
        name: clang-tidy
        language: system
        entry: run-clang-tidy -p build/Debug src/ tests/
        types_or: [c++, c]
        exclude: ^build/
        pass_filenames: false
